run on terminal

# pip install numpy matplotlip

In [9]:
!pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.9 kB 325.1 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 405.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
    --------------------------------------- 0.3/16.3 MB 8.6 MB/s eta 0:00:02
   - -------------------------------------- 0.7/16.3 MB 7.8 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/16.3 MB 7.3 MB/s eta 0:00:03
   -- ------------------------------------- 1.1/16.3 MB 6.3 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/16.3 MB 5.6 MB/s eta 0:00:03
   --- ------------------------------------ 1.4/16.3 MB 5.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/16.3 MB 5.2 MB/s eta 0:00:03
   ---

In [10]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicling 
- boolean filter


In [11]:
x= np.array([1,2,3,4,5])

In [12]:
a=np.array([[1,2,3,],[4,5,6,]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [14]:
z=[0,1,2,3,4,5,6,7,8,9]
nz=np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arrange
- linspace


In [15]:
np.random.rand(3,3)

array([[0.73454445, 0.99385887, 0.08769399],
       [0.57833736, 0.60489667, 0.49904653],
       [0.89795177, 0.10050655, 0.5114786 ]])

In [16]:
r1=np.random.randint(-5,6,(5,5))
print(r1)

[[ 4  2  5  3  3]
 [ 1  3  4  3 -4]
 [ 1 -1 -3 -4  2]
 [-5 -5  2  4 -3]
 [ 2 -4  4  5 -2]]


In [17]:
#start,stop,gap
np.arange(0,50,.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [19]:
#start,stop,number_of_item
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

array attributes
- shape
- dtype
- ndim
- size

basic operation
- sun
- mean
- min
- max
- std
- reshape
- transpose
- flatten


In [20]:
x.dtype

dtype('int64')

In [21]:
x=np.random.rand(3,3)
x.dtype

dtype('float64')

In [22]:
x.ndim

2

In [25]:
z = np.random.randint(1,5,(3,3,3))
z.ndim

3

In [27]:
z.size

27

In [28]:
z.sum()

np.int64(68)

In [26]:
a=np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))#sum of column -wise
print(a.sum(axis=1))# sum of row -wise

print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())
# all the method can be used with axis

3.510919591750044
[1.47494217 0.93526988 1.10070754]
[1.7476693  1.76325029]
0.585153265291674
0.933086562931657
0.16762097965158995
0.29348142898539786
0.08613134915931114


In [29]:
z=np.random.randint(11,99,(5,5))
print(z)
print('transpose')
print(z.transpose())# or print(z.t)
print('flattened')
print(z.flatten())

[[89 95 33 25 61]
 [47 62 30 22 71]
 [57 48 26 64 21]
 [21 64 69 70 56]
 [55 38 18 31 78]]
transpose
[[89 47 57 21 55]
 [95 62 48 64 38]
 [33 30 26 69 18]
 [25 22 64 70 31]
 [61 71 21 56 78]]
flattened
[89 95 33 25 61 47 62 30 22 71 57 48 26 64 21 21 64 69 70 56 55 38 18 31
 78]


In [34]:
a=np.random.randint(1,10, (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))
print(a.reshape(10,2))
print(a.reshape(5,2,2))


[[3 9 6 7 7]
 [6 5 8 9 6]
 [3 3 7 4 7]
 [9 9 3 7 7]]
[3 9 6 7 7 6 5 8 9 6 3 3 7 4 7 9 9 3 7 7]
[[3 9 6 7]
 [7 6 5 8]
 [9 6 3 3]
 [7 4 7 9]
 [9 3 7 7]]
[[3 9 6 7 7 6 5 8 9 6]
 [3 3 7 4 7 9 9 3 7 7]]
[[3 9]
 [6 7]
 [7 6]
 [5 8]
 [9 6]
 [3 3]
 [7 4]
 [7 9]
 [9 3]
 [7 7]]
[[[3 9]
  [6 7]]

 [[7 6]
  [5 8]]

 [[9 6]
  [3 3]]

 [[7 4]
  [7 9]]

 [[9 3]
  [7 7]]]


In [35]:
a=np.array([[1,2],[3,4]])
b=np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [36]:
# when using 2 matrix the shape 
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a@b)
print(a.dot(b))


[[7 4]
 [9 7]]
[[-5  0]
 [-3  1]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [ ]:
# when using matrix and scalar
print(a+10)# broadcasting
print(a*10)# broadcasting
print(a/10)
print(a-10)

In [39]:
# indexing
print(a[0,0])
print(a[-1,-1])

1
4


In [46]:
#slicing
x=np.random.randint(1,10,(5,5))
print(x)
print(x[:,0])
print(x[:,-1])
print(x[:,:3])
print(x[:-1,:-1])

[[8 5 1 5 5]
 [2 1 5 7 6]
 [3 8 6 3 8]
 [4 4 4 5 9]
 [7 2 4 9 1]]
[8 2 3 4 7]
[5 6 8 9 1]
[[8 5 1]
 [2 1 5]
 [3 8 6]
 [4 4 4]
 [7 2 4]]
[[8 5 1 5]
 [2 1 5 7]
 [3 8 6 3]
 [4 4 4 5]]
